name : user_srv
port : 0
ip : 10.3.189.8

mysql :
  host : 127.0.0.1
  port : 3306
  user : root
  pass : 123456
  database : 2201a

consul :
  consul_host : 127.0.0.1
  consul_port : 8500
  tags :
    - user_srv
    - shop
    - wei